license="${mod_license}"

[[mods]]
modId="shareddeath"
version="${mod_version}"
displayName="Shared Death Mod"
authors="${mod_authors}"
description='''Если один игрок умирает на сервере, то умирают все остальные игроки.'''

[[dependencies.shareddeath]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.shareddeath]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[mods]]
modId="informator"
version="${mod_version}"
displayName="Informator"
authors="${mod_authors}"
description='''При входе в незер портал сообщает координаты ближайшей незер крепости.'''

[[dependencies.informator]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.informator]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"